stages:
  - build

Building:
  stage: build
  variables:
    COMPOSER_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/composer"
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - ${COMPOSER_CACHE_DIR}
  image:  composer:1.8
  script:
    - composer install -o --no-dev
  artifacts:
    paths:
     - $ARTIFACT_PATH
  only: ['development', 'tags']
