before_script:
  - docker info

build_image:
  script:
    - git clone https://github.com/LaraDock/laradock.git
    - cd laradock
    - docker-compose up -d  nginx
    - docker exec --user=laradock workspace bash
