// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'

//post.ja
export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_POST = 'CREATE_POST'

export const BUSCAR_VISITANTES = 'BUSCAR_VISITANTES'

//Snack Bar
export const SHOW_SNACK_BAR = 'SHOW_SNACK_BAR'
export const CLOSE_SNACK_BAR = 'CLOSE_SNACK_BAR'

//Toolbar
export const VISIBLE_TABS = 'VISIBLE_TABS'

//Notifications
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const MARK_AS_READ = 'MARK_AS_READ'
export const MARK_ALL_AS_READ = 'MARK_ALL_AS_READ'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'

//Members
export const FETCH_PROFESSIONS = 'FETCH_PROFESSIONS'
export const FETCH_NEIGHBORHOODS = 'FETCH_NEIGHBORHOODS'
export const FETCH_MEMBER_DETAIL = 'FETCH_MEMBER_DETAIL'
export const FETCH_MARITAL_STATUS = 'FETCH_MARITAL_STATUS'
export const FETCH_TRUSTS = 'FETCH_TRUSTS'
export const SAVE_MEMBER = 'SAVE_MEMBER'
export const FETCH_GENDERS = 'FETCH_GENDERS'
export const FETCH_SCHOOLINGS = 'FETCH_SCHOOLINGS'
export const BUSCAR_TIPOS_CADASTROS = 'BUSCAR_TIPOS_CADASTROS'
export const BUSCAR_CARGOS_MINISTERIAIS = 'BUSCAR_CARGOS_MINISTERIAIS'
export const BUSCAR_SITUACOES_MEMBROS = 'BUSCAR_SITUACOES_MEMBROS'
export const DESATIVAR_MEMBRO = 'DESATIVAR_MEMBRO'

//Endereco
export const BUSCAR_ESTADOS = 'BUSCAR_ESTADOS'
export const BUSCAR_CIDADES = 'BUSCAR_CIDADES'
export const BUSCAR_CIDADES_NATURALIDADE = 'BUSCAR_CIDADES_NATURALIDADE'
export const BUSCAR_ENDERECO_CEP = 'BUSCAR_ENDERECO_CEP'
export const ATUALIZAR_CEP = 'ATUALIZAR_CEP'
export const ATUALIZAR_ESTADO = 'ATUALIZAR_ESTADO'
export const ATUALIZAR_CIDADE = 'ATUALIZAR_CIDADE'
export const ATUALIZAR_BAIRRO = 'ATUALIZAR_BAIRRO'
export const ATUALIZAR_ENDERECO = 'ATUALIZAR_ENDERECO'
export const ATUALIZAR_NUMERO = 'ATUALIZAR_NUMERO'
export const DESABILITA_FORM = 'DESABILITA_FORM'
export const SET_LAT_LNG = 'SET_LAT_LNG'

//Departments
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS'
export const PERMISSIONS = 'PERMISSIONS'

//Financeiro
export const BUSCAR_CATEGORIAS_FINANCEIRO = 'BUSCAR_CATEGORIAS_FINANCEIRO'
export const CADASTRAR_CATEGORIA_FINANCEIRO = 'CADASTRAR_CATEGORIA_FINANCEIRO'

//Setores
export const FETCH_SETORES = 'FETCH_SETORES'
export const CADASTRAR_SETOR = 'CADASTRAR_SETOR'

export const UPDATE_FILES = 'UPDATE_FILES'

//Igrejas
export const BUSCAR_IGREJAS = 'BUSCAR_IGREJAS'
export const CADASTRAR_IGREJAS = 'CADASTRAR_IGREJAS'
export const REMOVER_IGREJA_ARRAY = 'REMOVER_IGREJA_ARRAY'

//User
export const BUSCA_PASTORES = 'BUSCA_PASTORES'










// lang.js
export const SET_LOCALE = 'SET_LOCALE'
