// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'

//post.ja
export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_POST = 'CREATE_POST'

export const BUSCAR_VISITANTES = 'BUSCAR_VISITANTES'

//Snack Bar
export const SHOW_SNACK_BAR = 'SHOW_SNACK_BAR'
export const CLOSE_SNACK_BAR = 'CLOSE_SNACK_BAR'

//Toolbar
export const VISIBLE_TABS = 'VISIBLE_TABS'

//Notifications
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const MARK_AS_READ = 'MARK_AS_READ'
export const MARK_ALL_AS_READ = 'MARK_ALL_AS_READ'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'

//Members
export const FETCH_PROFESSIONS = 'FETCH_PROFESSIONS'
export const FETCH_STATES = 'FETCH_STATES'
export const FETCH_CITIES = 'FETCH_CITIES'
export const FETCH_NEIGHBORHOODS = 'FETCH_NEIGHBORHOODS'
export const FETCH_MEMBER_DETAIL = 'FETCH_MEMBER_DETAIL'
export const FETCH_MARITAL_STATUS = 'FETCH_MARITAL_STATUS'
export const FETCH_TRUSTS = 'FETCH_TRUSTS'
export const SAVE_MEMBER = 'SAVE_MEMBER'
export const FETCH_GENDERS = 'FETCH_GENDERS'
export const FETCH_SCHOOLINGS = 'FETCH_SCHOOLINGS'
export const BUSCAR_TIPOS_CADASTROS = 'BUSCAR_TIPOS_CADASTROS'
export const BUSCAR_CARGOS_MINISTERIAIS = 'BUSCAR_CARGOS_MINISTERIAIS'

//Departments
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS'
export const PERMISSIONS = 'PERMISSIONS'

//Setores
export const FETCH_SETORES = 'FETCH_SETORES'

//Igrejas
export const BUSCAR_IGREJAS = 'BUSCAR_IGREJAS'










// lang.js
export const SET_LOCALE = 'SET_LOCALE'
